### ISSUE TITLE
no sound in MF 101.0.1

### ISSUE THREAD

**Issue by melifarrro** [freaktechnik/notification-sounds#192]
in version 101.0.1 of mozilla firefox sound is not worked. I click button "test play" - no effect.

**Comment by freaktechnik** [comment]
With the amount of information you've provided all I can say is that it works fine for me.

**Comment by melifarrro** [comment]
in linux (ubuntu)?

**Comment by freaktechnik** [comment]
Yes.

**Comment by melifarrro** [comment]
yes, i found my problem, sorry/
