### ISSUE TITLE
Option to always play download notification sound

### ISSUE THREAD

**Issue by LeBaux** [freaktechnik/notification-sounds#23]
Moving issue from [firefox addon page](https://addons.mozilla.org/en-US/firefox/addon/notification-sound/reviews/934505/) for sake of or better communication. I'm currently testing the beta. I wouldn't mind, if the download complete notification played even if the window is focused. Current version of Firefox makes is very subtle that download is complete. Before this addon, I was using [Download sound](https://addons.mozilla.org/en-US/firefox/addon/download-sound/). Only issue there was I couldn't change the notification sound. Maybe you can even split this into separate extension - I am happy the way it is, but some people might want just the download notification. Also thanks for the prompt reply and release of beta, very nice of you!

**Comment by freaktechnik** [comment]
Just so I get this right - you'd want an additional option to always play the sound? I should consider that.

Further, I do not think I should split this out, since downloads used to give you a notification on some systems and as I said, I had initially considered this as a thing the extension should do.

**Comment by LeBaux** [comment]
You got it right! I prefer to receive notification always, but yeah, some people might prefer notification only if firefox window is not focused. Having it an option (checkbox) is the best way to go.

The whole reason I went looking for extension to play some audio cue for finished download is the demise of pre-webextension addons, that offered both audio and visual cues (for example [download statusbar](https://addons.mozilla.org/cs/firefox/addon/download-statusbar/)). Thanks again!

**Comment by freaktechnik** [comment]
This is in 1.1.0pre02

**Comment by freaktechnik** [comment]
And in the now released 1.1.0 non-beta version
