### ISSUE TITLE
Default sound not work on Windows

### ISSUE THREAD

**Issue by ti00652** [freaktechnik/notification-sounds#29]
Default sound not work on Windows 7 64bit.
Firefox version: 	56.0.2
Notification Sound version: 1.0.2

**Comment by freaktechnik** [comment]
It is working for me on Windows 10. I wonder if Window 7 does not support flac. Can you play https://raw.githubusercontent.com/freaktechnik/notification-sounds/master/pop.flac ?

**Comment by ti00652** [comment]
Yes, i can play. If I download and browse the file, it works (like mp3 and wav).

**Comment by freaktechnik** [comment]
And it does not play when you press the play button in the settings?

**Comment by ti00652** [comment]
No, i tried it there.
