### ISSUE TITLE
Custom Sound not work in JSFiddle example

### ISSUE THREAD

**Issue by ti00652** [freaktechnik/notification-sounds#30]
Custom Sound not work in [JSFiddle example](http://jsfiddle.net/y5gj9tj1/5) (play default sound).

**Comment by freaktechnik** [comment]
For which button?

**Comment by freaktechnik** [comment]
If it's the service worker one, then it is expected. Also, is this a dupe of #29 ?

**Comment by ti00652** [comment]
"Normal" and "Custom Sound" buttons play the same sound, instead of setting it in "EXTERNAL_SOUND" variable. A file exists, playable: http://www.sample-videos.com/audio/mp3/crowd-cheering.mp3.

**Comment by freaktechnik** [comment]
You need the latest beta version for the custom sound to work.
