### ISSUE TITLE
Sound not playing 

### ISSUE THREAD

**Issue by mmmraa** [freaktechnik/notification-sounds#41]
Hi,

Me and some friends have not been able to play sounds any longer. It only plays the default sound and not the custom sound.

**Comment by mmmraa** [comment]
We are using windows 10, firefox quantum 61.0.1 and MP3 file. Preview is not working.

**Comment by freaktechnik** [comment]
Thank you, I've been able to reproduce it now and will release a fix shortly.

**Comment by freaktechnik** [comment]
1.2.3 was just released and should fix this. It should get installed automatically when checking for extension updates.
