### ISSUE TITLE
Sound not playing

### ISSUE THREAD

**Issue by gj9999** [freaktechnik/notification-sounds#43]
Hi when I try to play the sound (default or custom) under the sound section of the options I get silence and a red error bar saying "The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission"

**Comment by freaktechnik** [comment]
Your system resp. Firefox build does not support the playback of FLAC files then. One user had success in fixing that by installing VLC.

**Comment by freaktechnik** [comment]
Oh wait, I misread the error. On what Firefox version is that, and do you have background playback disallowed by pref?

**Comment by gj9999** [comment]
Hi, I'm running 61.0.2.  I'm not aware that I have background playback disallowed - is that an FF config setting?

**Comment by freaktechnik** [comment]
It is, however in the meantime it would've been resolved if you were on FF 63 -> https://bugzilla.mozilla.org/show_bug.cgi?id=1466926 ; else you weren't affected in the first place.

Does it still show that error with the latest extension version (1.3.3)? If yes I truly have no idea why that error would be shown.

**Comment by gj9999** [comment]
Thanks for your solution, for some reason media.autoplay was marked as false, now fixed.  Very grateful

**Comment by freaktechnik** [comment]
Glad you could figure it out! Sorry about things being complicated ;)
