### ISSUE TITLE
Object Event

### ISSUE THREAD

**Issue by mmmraa** [freaktechnik/notification-sounds#44]
Sup bro!

You were very useful last Sunday(thank you for that). Today i am receiving this error(Object event), do you suggest me to do something, or is it the app's problem?. I am using firefox quantum 6.1.2, i previewed the sound but it only sounds the default notification sound. It was working fine until i tried to change the sound. Attached screenshot

![object event](https://user-images.githubusercontent.com/42117099/44001922-b8ccc706-9df7-11e8-920a-9df16387adc2.PNG)

**Comment by freaktechnik** [comment]
This error means it couldn't properly store the sound, I'll have to look into making that more readable. I assume this is on the latest version (1.3.0)?

**Comment by mmmraa** [comment]
Yes. It is the latest version of the add-on 1.3.0

**Comment by freaktechnik** [comment]
So if this is a storage issue, you won't see something like this: 
![image](https://user-images.githubusercontent.com/640949/44002210-b47bc8b2-9e3f-11e8-8264-45c6355016dc.png)

I'll try to get an update together that makes it a bit easier to find the full error...

**Comment by freaktechnik** [comment]
I've just published 1.3.1. It should show you a proper error message, which will make it much clearer what the issue is.
