### ISSUE TITLE
Notification Sound

### ISSUE THREAD

**Issue by NareshAlwyn** [freaktechnik/notification-sounds#55]
We really need this feature and there are a lot of associates who are working here more than 100 hundreds. This notification sound works sometimes but not always. Earlier it was working always but after the latest update to 67.0.1 64 bit it only works occasionally. Therefore we are not able to be notified when we receive a case hence we are missing cases which is crucial to our business please fix this or we might have to shift the browser which we really don't want to.

**Comment by freaktechnik** [comment]
Could you point me to a website where it only works some times? It may also only work intermittently due to the known limitations. If this is really this important a feature, you may want to look into asking the supplier of your web solution to add support for a notification sound being played on their website.

**Comment by NareshAlwyn** [comment]
It is an internal application called paragon.

**Comment by NareshAlwyn** [comment]
Can you guys please fix this as we really require firefox since we feel comfortable on it and do not want to switch now.

**Comment by freaktechnik** [comment]
Sadly there is nothing I could reproduce, so I can not attempt to fix it.

**Comment by freaktechnik** [comment]
All I can do is to point you to https://jsfiddle.net/y5gj9tj1/10/ where the top three buttons in the bottom right should produce a notification that makes a sound.

**Comment by NareshAlwyn** [comment]
Thank you let me check.

**Comment by NareshAlwyn** [comment]
Finally it has worked when I downgraded firefox to version 57....please if possible fix the latest 67 version aswell. Thank you and have a nice day.

**Comment by freaktechnik** [comment]
Sorry, I still have nothing to work with here.
