### ISSUE TITLE
Suggest update scanner add-on ID in add-on selector

### ISSUE THREAD

**Issue by MrShuzo** [freaktechnik/notification-sounds#77]
Hey!
Just wanted to let you know that this plugin is working with the Update Scanner plugin: https://addons.mozilla.org/de/firefox/addon/update-scanner/.
Very nice plugin you made!

**Comment by freaktechnik** [comment]
Thanks for the heads up. Seems that's been in there for a while now:
https://github.com/sneakypete81/updatescanner/commit/f88709d62fa7870d83a70f948c461e0ae585cd23

I have to admit, even though I use the extension myself, I don't have notification sounds enabled, so I haven't noticed.

**Comment by freaktechnik** [comment]
I've added a note on the AMO listing. I'll re-purpose this to add the ID of update scanner to the built-in recommended add-on IDs.
